version: 2
updates:

  # mandatory check for github actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'VKCOM/vk-sec'
      - 'VKCOM/<team_service_user>'

  # next part can be used multiple times
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-type: 'direct'
    reviewers:
      - 'VKCOM/vk-sec'
      - 'VKCOM/<team_service_user>'
