version: "3.9"
services:
#    app:
#        build: ./.docker/nginx-unit
#        volumes:
#            - .:/var/www/html
#        working_dir: /var/www/html
#        depends_on:
#            - db
#        ports:
#            - 8081:80
    db:
        image: mysql:5.7.42
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./.docker/mysql/data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: made_with_love
            MYSQL_DATABASE: miniapp
    php:
        build:
            context: ./.docker/php/
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/html/
        volumes:
            - .:/var/www/html
        depends_on:
            - db
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8081:80
        depends_on:
            - php
        volumes:
            - .:/var/www/html
            - ./.docker/nginx/:/etc/nginx/conf.d/
